//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffee.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public string idBan { get; set; }
        public string TenBan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
