//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffee.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string idHoaDon { get; set; }
        public string TenBan { get; set; }
        public string TenThucDon { get; set; }
        public System.DateTime ThoiDiemDen { get; set; }
        public Nullable<System.DateTime> ThoiDiemRa { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual ThucDon ThucDon { get; set; }
    }
}
