//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffee.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucDon
    {
        public string idThucDon { get; set; }
        public string TenThucDon { get; set; }
        public string GiaTien { get; set; }
    
        public virtual DanhSach DanhSach { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
